//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cliente.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Aceptar_EG {
            get {
                return ResourceManager.GetString("Aceptar_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string Agregar_EG {
            get {
                return ResourceManager.GetString("Agregar_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are empty fields.
        /// </summary>
        public static string AlertaCamposVacios_MSJ {
            get {
                return ResourceManager.GetString("AlertaCamposVacios_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The room code cannot be left empty, please enter a room code..
        /// </summary>
        public static string AlertaCodigoSalaNoIntroducido_MSJ {
            get {
                return ResourceManager.GetString("AlertaCodigoSalaNoIntroducido_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email cannot be empty, it is necessary to enter a valid email address..
        /// </summary>
        public static string AlertaCorreoEsRequerido_MSJ {
            get {
                return ResourceManager.GetString("AlertaCorreoEsRequerido_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do not select any player, select a player first.
        /// </summary>
        public static string AlertaFilaDeAmigoNoSeleccionada_MSJ {
            get {
                return ResourceManager.GetString("AlertaFilaDeAmigoNoSeleccionada_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I did not select any friend request, select a request first.
        /// </summary>
        public static string AlertaFilaDeSolicitudNoSeleccionada_MSJ {
            get {
                return ResourceManager.GetString("AlertaFilaDeSolicitudNoSeleccionada_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid password, enter a password of at least 6 characters with a combination of at least one letter, one number, and one special character..
        /// </summary>
        public static string AlertaFormatoContraseniaNoValido_MSJ {
            get {
                return ResourceManager.GetString("AlertaFormatoContraseniaNoValido_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This account is banned.
        /// </summary>
        public static string AlertaJugadorBaneado_MSJ {
            get {
                return ResourceManager.GetString("AlertaJugadorBaneado_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An account already exists with the information entered..
        /// </summary>
        public static string AlertaLaCuentaYaExiste_MSJ {
            get {
                return ResourceManager.GetString("AlertaLaCuentaYaExiste_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username cannot be the same as your account name..
        /// </summary>
        public static string AlertaMismoNombreUsuarioDestino_MSJ {
            get {
                return ResourceManager.GetString("AlertaMismoNombreUsuarioDestino_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user name you are looking for does not exist in the system registry..
        /// </summary>
        public static string AlertaNoExisteNombreUsuario_MSJ {
            get {
                return ResourceManager.GetString("AlertaNoExisteNombreUsuario_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is none for the code entered, check the code and try again..
        /// </summary>
        public static string AlertaNoExisteSala_MSJ {
            get {
                return ResourceManager.GetString("AlertaNoExisteSala_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There must be exactly two players, otherwise the game cannot start..
        /// </summary>
        public static string AlertaNoHayDosJugadores_MSJ {
            get {
                return ResourceManager.GetString("AlertaNoHayDosJugadores_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I did not enter a user name in the search engine, please enter one to proceed..
        /// </summary>
        public static string AlertaNoSeIngresoNombreUsuario_MSJ {
            get {
                return ResourceManager.GetString("AlertaNoSeIngresoNombreUsuario_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A failure occurred and the selected player could not be added to your friends list, try again at another time..
        /// </summary>
        public static string AlertaNoSePudoAgregarAmistad_MSJ {
            get {
                return ResourceManager.GetString("AlertaNoSePudoAgregarAmistad_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A failure occurred and the selected player could not be deleted from your friends list, try again at another time..
        /// </summary>
        public static string AlertaNoSePudoBorrarAmistad_MSJ {
            get {
                return ResourceManager.GetString("AlertaNoSePudoBorrarAmistad_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A failure occurred and the selected friend request could not be deleted from your list of requests, please try again at a later time..
        /// </summary>
        public static string AlertaNoSePudoBorrarSolicitud_MSJ {
            get {
                return ResourceManager.GetString("AlertaNoSePudoBorrarSolicitud_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A failure occurred and the request could not be sent, please try again later..
        /// </summary>
        public static string AlertaNoSePudoEnviarSolicitud_MSJ {
            get {
                return ResourceManager.GetString("AlertaNoSePudoEnviarSolicitud_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a At the moment the game only supports two users per room and it is already full..
        /// </summary>
        public static string AlertaSalaLlena_MSJ {
            get {
                return ResourceManager.GetString("AlertaSalaLlena_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A request has already been sent, it cannot be resubmitted..
        /// </summary>
        public static string AlertaYaExisteUnaSolicitudEnviada_MSJ {
            get {
                return ResourceManager.GetString("AlertaYaExisteUnaSolicitudEnviada_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string Amigos_EG {
            get {
                return ResourceManager.GetString("Amigos_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Atras_EG {
            get {
                return ResourceManager.GetString("Atras_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend Friend in ban status.
        /// </summary>
        public static string AvisoAmigoBaneado_MSJ {
            get {
                return ResourceManager.GetString("AvisoAmigoBaneado_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend in normal state.
        /// </summary>
        public static string AvisoAmigoNormal_MSJ {
            get {
                return ResourceManager.GetString("AvisoAmigoNormal_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has been added to friends list.
        /// </summary>
        public static string AvisoAmistadAgregada_MSJ {
            get {
                return ResourceManager.GetString("AvisoAmistadAgregada_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected player has been deleted from your friends list..
        /// </summary>
        public static string AvisoAmistadBorrada_MSJ {
            get {
                return ResourceManager.GetString("AvisoAmistadBorrada_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        public static string AvisoBienvenido_MSJ {
            get {
                return ResourceManager.GetString("AvisoBienvenido_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The room code will be lost, and a new one will be generated. This action cannot be undone, are you sure you want to cancel the game?.
        /// </summary>
        public static string AvisoConfirmarCancelacionJuego_MSJ {
            get {
                return ResourceManager.GetString("AvisoConfirmarCancelacionJuego_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to remove this player from your friends list?.
        /// </summary>
        public static string AvisoConfirmarEliminacion_MSJ {
            get {
                return ResourceManager.GetString("AvisoConfirmarEliminacion_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to remove this request from your request list?.
        /// </summary>
        public static string AvisoConfirmarEliminacionSolicitud_MSJ {
            get {
                return ResourceManager.GetString("AvisoConfirmarEliminacionSolicitud_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account successfully registered in the system..
        /// </summary>
        public static string AvisoCuentaRegistradaExitosamente_MSJ {
            get {
                return ResourceManager.GetString("AvisoCuentaRegistradaExitosamente_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The form was filled out incorrectly please check it..
        /// </summary>
        public static string AvisoFormularioLlenadoMal_MSJ {
            get {
                return ResourceManager.GetString("AvisoFormularioLlenadoMal_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The application language has changed, please press back to reload..
        /// </summary>
        public static string AvisoIdiomaCambiado_MSJ {
            get {
                return ResourceManager.GetString("AvisoIdiomaCambiado_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exiting the game, thank you for playing minesweeper..
        /// </summary>
        public static string AvisoSalida_MSJ {
            get {
                return ResourceManager.GetString("AvisoSalida_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected friend request has been deleted from your list of requests..
        /// </summary>
        public static string AvisoSolicitudAmistadBorrada_MSJ {
            get {
                return ResourceManager.GetString("AvisoSolicitudAmistadBorrada_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The request to the searched user has been sent successfully..
        /// </summary>
        public static string AvisoSolicitudEnviada_MSJ {
            get {
                return ResourceManager.GetString("AvisoSolicitudEnviada_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flags :.
        /// </summary>
        public static string Banderas_EG {
            get {
                return ResourceManager.GetString("Banderas_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Baneado.
        /// </summary>
        public static string Baneado_MSJCONST {
            get {
                return ResourceManager.GetString("Baneado_MSJCONST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MineSweeper.
        /// </summary>
        public static string Buscaminas_EG {
            get {
                return ResourceManager.GetString("Buscaminas_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change appearance.
        /// </summary>
        public static string CambiarApariencia_EG {
            get {
                return ResourceManager.GetString("CambiarApariencia_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancelar_EG {
            get {
                return ResourceManager.GetString("Cancelar_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel Game.
        /// </summary>
        public static string CancelarJuego_EG {
            get {
                return ResourceManager.GetString("CancelarJuego_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0.
        /// </summary>
        public static string Cero_MSJCONST {
            get {
                return ResourceManager.GetString("Cero_MSJCONST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string Cerrar_EG {
            get {
                return ResourceManager.GetString("Cerrar_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string Chat_EG {
            get {
                return ResourceManager.GetString("Chat_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation code.
        /// </summary>
        public static string CodigoConfirmacion_EG {
            get {
                return ResourceManager.GetString("CodigoConfirmacion_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby Code.
        /// </summary>
        public static string CodigoSala_EG {
            get {
                return ResourceManager.GetString("CodigoSala_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password.
        /// </summary>
        public static string ConfirmarContrasenia_EG {
            get {
                return ResourceManager.GetString("ConfirmarContrasenia_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenders.
        /// </summary>
        public static string Contendiente_EG {
            get {
                return ResourceManager.GetString("Contendiente_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Contrasenia_EG {
            get {
                return ResourceManager.GetString("Contrasenia_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Correo_EG {
            get {
                return ResourceManager.GetString("Correo_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minesweeper game invitation code.
        /// </summary>
        public static string CorreoAsuntoCodigoInvitacion_MSJ {
            get {
                return ResourceManager.GetString("CorreoAsuntoCodigoInvitacion_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minesweeper Game Registration Code.
        /// </summary>
        public static string CorreoAsuntoCodigoRegistroCuenta_MSJ {
            get {
                return ResourceManager.GetString("CorreoAsuntoCodigoRegistroCuenta_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a has invited you to play minesweeper. Enter the following room code:.
        /// </summary>
        public static string CorreoMensajeCodigoInvitacion_MSJ {
            get {
                return ResourceManager.GetString("CorreoMensajeCodigoInvitacion_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your minesweeper registration code is :.
        /// </summary>
        public static string CorreoMensajeCodigoRegistroCuenta_MSJ {
            get {
                return ResourceManager.GetString("CorreoMensajeCodigoRegistroCuenta_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Lobby.
        /// </summary>
        public static string CrearSala_EG {
            get {
                return ResourceManager.GetString("CrearSala_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credits.
        /// </summary>
        public static string Creditos_EG {
            get {
                return ResourceManager.GetString("Creditos_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Two Players.
        /// </summary>
        public static string DosJugadores_EG {
            get {
                return ResourceManager.GetString("DosJugadores_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Eliminar_EG {
            get {
                return ResourceManager.GetString("Eliminar_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Draw.
        /// </summary>
        public static string Empate_EG {
            get {
                return ResourceManager.GetString("Empate_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send confirmation code.
        /// </summary>
        public static string EnviarCodigo_EG {
            get {
                return ResourceManager.GetString("EnviarCodigo_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send message.
        /// </summary>
        public static string EnviarMensaje_EG {
            get {
                return ResourceManager.GetString("EnviarMensaje_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send friend request.
        /// </summary>
        public static string EnviarSolicitud_EG {
            get {
                return ResourceManager.GetString("EnviarSolicitud_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect button name in JuegoGUI.xaml.
        /// </summary>
        public static string ErrorBMExcepcionNombreIncorrectoBoton_MSJ {
            get {
                return ResourceManager.GetString("ErrorBMExcepcionNombreIncorrectoBoton_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid button reference when revealing the cell in the table (the button points to an invalid cell)..
        /// </summary>
        public static string ErrorBMExcepcionReferenciaInvalidaBoton_MSJ {
            get {
                return ResourceManager.GetString("ErrorBMExcepcionReferenciaInvalidaBoton_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The fields cannot be filled with the space character only, as they will be blank..
        /// </summary>
        public static string ErrorCamposConCaracterEspacio_MSJ {
            get {
                return ResourceManager.GetString("ErrorCamposConCaracterEspacio_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The confirmation code sent to the email does not match the confirmation code entered..
        /// </summary>
        public static string ErrorCodigosConfirmacionDiferentes_MSJ {
            get {
                return ResourceManager.GetString("ErrorCodigosConfirmacionDiferentes_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match.
        /// </summary>
        public static string ErrorContraseniaNoCoincide_MSJ {
            get {
                return ResourceManager.GetString("ErrorContraseniaNoCoincide_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The account could not be registered, please try again at a later time..
        /// </summary>
        public static string ErrorCuentaNoRegistrada_MSJ {
            get {
                return ResourceManager.GetString("ErrorCuentaNoRegistrada_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username or password are not correct.
        /// </summary>
        public static string ErrorDatosIncorrectos_MSJ {
            get {
                return ResourceManager.GetString("ErrorDatosIncorrectos_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email format is not valid.
        /// </summary>
        public static string ErrorFormatoCorreoInvalido_MSJ {
            get {
                return ResourceManager.GetString("ErrorFormatoCorreoInvalido_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was a failure and could not enter the room, try again at a later time..
        /// </summary>
        public static string ErrorIngresandoASala_MSJ {
            get {
                return ResourceManager.GetString("ErrorIngresandoASala_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en llamada de referencia TableroBucaminas no válida [fila, columna] al revelar.
        /// </summary>
        public static string ErrorLlamadaReferenciaBuscaminas_MSJCONST {
            get {
                return ResourceManager.GetString("ErrorLlamadaReferenciaBuscaminas_MSJCONST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot find server.
        /// </summary>
        public static string ErrorNoSeEncontroServidor_MSJ {
            get {
                return ResourceManager.GetString("ErrorNoSeEncontroServidor_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A failure occurred and the player could not be deleted from the room, try again at another time..
        /// </summary>
        public static string ErrorNoSePudoBorrarJugadorSala_MSJ {
            get {
                return ResourceManager.GetString("ErrorNoSePudoBorrarJugadorSala_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was a failure and the room could not be created..
        /// </summary>
        public static string ErrorNosePudoCrearLaSala_MSJ {
            get {
                return ResourceManager.GetString("ErrorNosePudoCrearLaSala_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is an error with the communication object of the server..
        /// </summary>
        public static string ErrorObjetoComunicacionConServidor_MSJ {
            get {
                return ResourceManager.GetString("ErrorObjetoComunicacionConServidor_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string Espaniol_EG {
            get {
                return ResourceManager.GetString("Espaniol_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting Player.
        /// </summary>
        public static string EsperandoJugador_EG {
            get {
                return ResourceManager.GetString("EsperandoJugador_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string Estado_EG {
            get {
                return ResourceManager.GetString("Estado_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Female.
        /// </summary>
        public static string Femenino_EG {
            get {
                return ResourceManager.GetString("Femenino_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot; : &quot;.
        /// </summary>
        public static string FormatoChat_MSJCONST {
            get {
                return ResourceManager.GetString("FormatoChat_MSJCONST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0:D2}{1:D2}.
        /// </summary>
        public static string FormatoCoordenadasDosDigito_MSJCONST {
            get {
                return ResourceManager.GetString("FormatoCoordenadasDosDigito_MSJCONST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0:D1}{1:D1}.
        /// </summary>
        public static string FormatoCoordenadasUnDigito_MSJCONST {
            get {
                return ResourceManager.GetString("FormatoCoordenadasUnDigito_MSJCONST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Winner.
        /// </summary>
        public static string Ganador_EG {
            get {
                return ResourceManager.GetString("Ganador_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gener.
        /// </summary>
        public static string Genero_EG {
            get {
                return ResourceManager.GetString("Genero_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string Ingles_EG {
            get {
                return ResourceManager.GetString("Ingles_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the room code.
        /// </summary>
        public static string IngresarCodigoSala_EG {
            get {
                return ResourceManager.GetString("IngresarCodigoSala_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter user name.
        /// </summary>
        public static string IngresarNombreUsuario_EG {
            get {
                return ResourceManager.GetString("IngresarNombreUsuario_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Game.
        /// </summary>
        public static string IniciarJuego_EG {
            get {
                return ResourceManager.GetString("IniciarJuego_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string IniciarSesion_EG {
            get {
                return ResourceManager.GetString("IniciarSesion_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite.
        /// </summary>
        public static string Invitar_EG {
            get {
                return ResourceManager.GetString("Invitar_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        public static string Jugador_EG {
            get {
                return ResourceManager.GetString("Jugador_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number one player.
        /// </summary>
        public static string Jugador1_EG {
            get {
                return ResourceManager.GetString("Jugador1_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The first player must start the game.
        /// </summary>
        public static string Jugador1DebeComenzar_MSJ {
            get {
                return ResourceManager.GetString("Jugador1DebeComenzar_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number two player.
        /// </summary>
        public static string Jugador2_EG {
            get {
                return ResourceManager.GetString("Jugador2_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players in the Lobby.
        /// </summary>
        public static string JugadoresSala_EG {
            get {
                return ResourceManager.GetString("JugadoresSala_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string Jugar_EG {
            get {
                return ResourceManager.GetString("Jugar_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friendlist.
        /// </summary>
        public static string ListaDeAmigos_EG {
            get {
                return ResourceManager.GetString("ListaDeAmigos_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List Friend.
        /// </summary>
        public static string ListarAmigos_EG {
            get {
                return ResourceManager.GetString("ListarAmigos_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List friend requests.
        /// </summary>
        public static string ListarSolicitudesAmistad_EG {
            get {
                return ResourceManager.GetString("ListarSolicitudesAmistad_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Male.
        /// </summary>
        public static string Masculino_EG {
            get {
                return ResourceManager.GetString("Masculino_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main Menu.
        /// </summary>
        public static string MenuPrincipal_EG {
            get {
                return ResourceManager.GetString("MenuPrincipal_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mines.
        /// </summary>
        public static string Minas_EG {
            get {
                return ResourceManager.GetString("Minas_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CasillaButton.
        /// </summary>
        public static string NombreBoton_MSJCONST {
            get {
                return ResourceManager.GetString("NombreBoton_MSJCONST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UserName.
        /// </summary>
        public static string NombreUsuario_EG {
            get {
                return ResourceManager.GetString("NombreUsuario_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no room corresponding to the code entered..
        /// </summary>
        public static string NoSeEncontroSala_MSJ {
            get {
                return ResourceManager.GetString("NoSeEncontroSala_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        public static string Opciones_EG {
            get {
                return ResourceManager.GetString("Opciones_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rival.
        /// </summary>
        public static string Oponente_EG {
            get {
                return ResourceManager.GetString("Oponente_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not registered in the game yet?.
        /// </summary>
        public static string PreguntaEresUsuario_EG {
            get {
                return ResourceManager.GetString("PreguntaEresUsuario_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register account.
        /// </summary>
        public static string RegistrarCuenta_EG {
            get {
                return ResourceManager.GetString("RegistrarCuenta_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string Registrarse_EG {
            get {
                return ResourceManager.GetString("Registrarse_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report user.
        /// </summary>
        public static string ReportarUsuario_EG {
            get {
                return ResourceManager.GetString("ReportarUsuario_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @&quot;/Imagenes/JuegoGUI/Bandera.png&quot;.
        /// </summary>
        public static string RutaImagenBandera_MSJCONST {
            get {
                return ResourceManager.GetString("RutaImagenBandera_MSJCONST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @&quot;/Imagenes/JuegoGUI/Bomba.png&quot;.
        /// </summary>
        public static string RutaImagenBomba_MSJCONST {
            get {
                return ResourceManager.GetString("RutaImagenBomba_MSJCONST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string Salir_EG {
            get {
                return ResourceManager.GetString("Salir_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Language.
        /// </summary>
        public static string SeleccionarIdioma_EG {
            get {
                return ResourceManager.GetString("SeleccionarIdioma_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friendship requests.
        /// </summary>
        public static string SolicitudesAmistad_EG {
            get {
                return ResourceManager.GetString("SolicitudesAmistad_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time :.
        /// </summary>
        public static string Tiempo_EG {
            get {
                return ResourceManager.GetString("Tiempo_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm game cancellation.
        /// </summary>
        public static string TituloVentanaCancelacionJuego_MSJ {
            get {
                return ResourceManager.GetString("TituloVentanaCancelacionJuego_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm deletion.
        /// </summary>
        public static string TituloVentanaConfirmarEliminacion_MSJ {
            get {
                return ResourceManager.GetString("TituloVentanaConfirmarEliminacion_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Deletion Request.
        /// </summary>
        public static string TituloVentanaConfirmarEliminacionSolicitud_MSJ {
            get {
                return ResourceManager.GetString("TituloVentanaConfirmarEliminacionSolicitud_MSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a your rival.
        /// </summary>
        public static string TuRival_EG {
            get {
                return ResourceManager.GetString("TuRival_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turn.
        /// </summary>
        public static string Turno_EG {
            get {
                return ResourceManager.GetString("Turno_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your user.
        /// </summary>
        public static string TuUsuario_EG {
            get {
                return ResourceManager.GetString("TuUsuario_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join the game.
        /// </summary>
        public static string UnirseAlJuego_EG {
            get {
                return ResourceManager.GetString("UnirseAlJuego_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sigle Player.
        /// </summary>
        public static string UnJugador_EG {
            get {
                return ResourceManager.GetString("UnJugador_EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string Usuario_EG {
            get {
                return ResourceManager.GetString("Usuario_EG", resourceCulture);
            }
        }
    }
}
